# ======================================================
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
    networks:
      - docker-network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp_volume:/var/www/html
    networks:
      - docker-network
    env_file:
      - ../secrets/.env
    secrets:
      - db_root_user
      - db_root_pwd
      - wp_admin_login
      - wp_admin_pwd
      - wp_user_pwd
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - docker-network
    env_file:
      - ../secrets/.env
    secrets:
      - db_root_user
      - db_root_pwd
      - wp_admin_login
      - wp_admin_pwd
    volumes:
      - DB:/var/lib/mysql
    restart: always

# ======================================================
volumes:
  wp_volume: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-mouh/data/wordpress
  DB: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-mouh/data/db

# ======================================================
secrets:
  db_root_user:
    file: ../secrets/db_root_user
  db_root_pwd:
    file: ../secrets/db_root_pwd
  wp_admin_login:
    file: ../secrets/wp_admin_login
  wp_admin_pwd:
    file: ../secrets/wp_admin_pwd
  wp_user_pwd:
    file: ../secrets/wp_user_pwd

# ======================================================
networks:
  docker-network:
    driver: bridge
